"""Update categories table structure

Revision ID: 067f8724cc18
Revises: d58e68ee718f
Create Date: 2025-08-17 17:21:40.293905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067f8724cc18'
down_revision = 'd58e68ee718f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now redundant since d58e68ee718f already created 
    # the complete categories table structure. This is kept as a no-op 
    # to maintain migration history integrity.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op, so downgrade is also a no-op
    pass
    # ### end Alembic commands ###
