"""Update categories table structure

Revision ID: 067f8724cc18
Revises: d58e68ee718f
Create Date: 2025-08-17 17:21:40.293905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067f8724cc18'
down_revision = 'd58e68ee718f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update categories table structure
    with op.batch_alter_table('categories', schema=None) as batch_op:
        # 添加缺失的列
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True, default=0))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        
        # 修改name字段长度
        batch_op.alter_column('name', type_=sa.String(length=50))
        
        # 创建索引
        batch_op.create_index('ix_categories_slug', ['slug'], unique=True)
        batch_op.create_index('ix_categories_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_categories_is_active', ['is_active'], unique=False)
    
    # 为现有记录设置默认值
    op.execute("UPDATE categories SET slug = LOWER(REPLACE(name, '&', 'and')) WHERE slug IS NULL")
    op.execute("UPDATE categories SET sort_order = 0 WHERE sort_order IS NULL")
    op.execute("UPDATE categories SET is_active = 1 WHERE is_active IS NULL")
    op.execute("UPDATE categories SET created_at = datetime('now') WHERE created_at IS NULL")
    
    # 现在设置slug为非空
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)
    
    # 添加category_id到blogs表
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_blogs_category_id', ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_blogs_category_id', 'categories', ['category_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除blogs表的category_id
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogs_category_id', type_='foreignkey')
        batch_op.drop_index('ix_blogs_category_id')
        batch_op.drop_column('category_id')
    
    # 移除categories表的新列
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_is_active')
        batch_op.drop_index('ix_categories_sort_order')
        batch_op.drop_index('ix_categories_slug')
        batch_op.drop_column('created_at')
        batch_op.drop_column('icon')
        batch_op.drop_column('is_active')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('description')
        batch_op.drop_column('slug')
        batch_op.alter_column('name', type_=sa.VARCHAR(length=100))
    
    # ### end Alembic commands ###
