"""Add DailyCheckIn model

Revision ID: 1eec418c5754
Revises: a020e14d8143
Create Date: 2026-06-16 20:50:29.389315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eec418c5754'
down_revision = 'a020e14d8143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_user_checkin_date')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkins_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkins_user_id'))

    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
