"""add BlogContent

Revision ID: 347052073ce1
Revises: ef691a7f20f9
Create Date: 2025-08-09 20:06:42.568252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347052073ce1'
down_revision = 'ef691a7f20f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_contents',
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_contents')
    # ### end Alembic commands ###
