"""check changes

Revision ID: 36e4bf7a5a90
Revises: e1a2b3c4d5e6
Create Date: 2025-12-14 10:53:08.925046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e4bf7a5a90'
down_revision = 'e1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_appeals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_appeals_updated_at'))
        batch_op.create_foreign_key('fk_appeals_appellant', 'users', ['appellant_id'], ['id'])
        batch_op.create_foreign_key('fk_appeals_log', 'admin_action_logs', ['log_id'], ['id'])
        batch_op.create_foreign_key('fk_appeals_decided_by', 'users', ['decided_by'], ['id'])

    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_logs_target_user', 'users', ['target_user_id'], ['id'])
        batch_op.create_foreign_key('fk_logs_admin', 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_blogs_category', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogs_category', type_='foreignkey')

    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logs_admin', type_='foreignkey')
        batch_op.drop_constraint('fk_logs_target_user', type_='foreignkey')

    with op.batch_alter_table('admin_action_appeals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appeals_decided_by', type_='foreignkey')
        batch_op.drop_constraint('fk_appeals_log', type_='foreignkey')
        batch_op.drop_constraint('fk_appeals_appellant', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_admin_action_appeals_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###
