"""add_image_hosting_table

Revision ID: 6c65a0d3ee38
Revises: 54a9780ba45d
Create Date: 2026-05-02 09:57:51.492704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c65a0d3ee38'
down_revision = 'e6c90c1ea618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_hosting',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_hosting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_hosting_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_hosting_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_hosting_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_hosting_ignore'), ['ignore'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_hosting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_hosting_ignore'))
        batch_op.drop_index(batch_op.f('ix_image_hosting_id'))
        batch_op.drop_index(batch_op.f('ix_image_hosting_created_at'))
        batch_op.drop_index(batch_op.f('ix_image_hosting_author_id'))

    op.drop_table('image_hosting')
    # ### end Alembic commands ###
