"""user ban system

Revision ID: 73a9f1b858f7
Revises: notification_settings
Create Date: 2025-08-31 19:17:33.451165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a9f1b858f7'
down_revision = 'notification_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=False),
    sa.Column('ban_until', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('is_lifted', sa.Boolean(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(), nullable=True),
    sa.Column('lifted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lifted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_bans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_bans_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_bans_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ban_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('ban_until')
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('user_bans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_bans_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_bans_admin_id'))

    op.drop_table('user_bans')
    # ### end Alembic commands ###
