"""添加 fish_api_key_encrypted 字段到 users 表

Revision ID: 7dd1f55053ca
Revises: e2b1ea62cb1d
Create Date: 2026-07-03 15:11:23.584060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd1f55053ca'
down_revision = 'e2b1ea62cb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fish_api_key_encrypted', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('fish_api_key_encrypted')

    # ### end Alembic commands ###
