"""add comment models

Revision ID: 7f96adcdf3c2
Revises: 8c1c9c0fd3a2
Create Date: 2025-11-02 11:09:16.078989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f96adcdf3c2'
down_revision = '8c1c9c0fd3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('root_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_comments.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['blog_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_status'), ['status'], unique=False)

    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['blog_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_like_comment_user')
    )
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_likes_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_likes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_comment_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_blogs_last_comment_at'), ['last_comment_at'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('exclude_from_all',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('admin_only_posting',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('notify_admin_on_post',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('notify_admin_on_post',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('admin_only_posting',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('exclude_from_all',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_last_comment_at'))
        batch_op.alter_column('is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('last_comment_at')
        batch_op.drop_column('comments_count')

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_likes_comment_id'))

    op.drop_table('comment_likes')
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_comments_status'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_root_id'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_blog_id'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_author_id'))

    op.drop_table('blog_comments')
    # ### end Alembic commands ###
