"""add vote tables

Revision ID: 8cf03635a45e
Revises: a33b41026460
Create Date: 2026-05-09 17:34:19.110038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf03635a45e'
down_revision = 'a33b41026460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_author_id'), ['author_id'], unique=False)

    op.create_table('vote_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vote_id', sa.String(length=9), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_options_vote_id'), ['vote_id'], unique=False)

    op.create_table('vote_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vote_id', sa.String(length=9), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['vote_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_id', 'user_id', name='uq_vote_user')
    )
    with op.batch_alter_table('vote_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_records_vote_id'), ['vote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_records_vote_id'))

    op.drop_table('vote_records')
    with op.batch_alter_table('vote_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_options_vote_id'))

    op.drop_table('vote_options')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_author_id'))

    op.drop_table('votes')
    # ### end Alembic commands ###
