"""add deleted in BlogLike

Revision ID: 8de1b128cb9a
Revises: 36e4bf7a5a90
Create Date: 2025-12-20 15:56:02.484909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de1b128cb9a'
down_revision = '36e4bf7a5a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
