"""add photo wall

Revision ID: a33b41026460
Revises: 6c65a0d3ee38
Create Date: 2026-05-02 12:34:28.055977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33b41026460'
down_revision = '6c65a0d3ee38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_wall_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=10), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image_hosting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_wall_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_wall_items_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_wall_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_wall_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_wall_items_ignore'), ['ignore'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_wall_items_image_id'), ['image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_wall_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_wall_items_image_id'))
        batch_op.drop_index(batch_op.f('ix_photo_wall_items_ignore'))
        batch_op.drop_index(batch_op.f('ix_photo_wall_items_id'))
        batch_op.drop_index(batch_op.f('ix_photo_wall_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_photo_wall_items_author_id'))

    op.drop_table('photo_wall_items')
    # ### end Alembic commands ###
