"""initial schema

Revision ID: a724a23de0a8
Revises: 
Create Date: 2025-08-09 20:32:57.569773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a724a23de0a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('blogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogs_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_ignore'), ['ignore'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_title'), ['title'], unique=False)

    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('blog_contents',
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('blog_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id', 'user_id', name='uq_blog_like_blog_user')
    )
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_likes_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_blog_likes_blog_id'))

    op.drop_table('blog_likes')
    op.drop_table('blog_contents')
    op.drop_table('invite_codes')
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_title'))
        batch_op.drop_index(batch_op.f('ix_blogs_ignore'))
        batch_op.drop_index(batch_op.f('ix_blogs_id'))
        batch_op.drop_index(batch_op.f('ix_blogs_created_at'))
        batch_op.drop_index(batch_op.f('ix_blogs_author_id'))

    op.drop_table('blogs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
