"""Add notification settings to users table

Revision ID: notification_settings
Revises: f63698f7f0bf
Create Date: 2024-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'notification_settings'
down_revision = 'f63698f7f0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_like', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('notify_edit', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('notify_delete', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('notify_admin', sa.Boolean(), nullable=True, default=True))
    
    # 为现有用户设置默认值
    op.execute("UPDATE users SET notify_like = 1 WHERE notify_like IS NULL")
    op.execute("UPDATE users SET notify_edit = 1 WHERE notify_edit IS NULL")
    op.execute("UPDATE users SET notify_delete = 1 WHERE notify_delete IS NULL")
    op.execute("UPDATE users SET notify_admin = 1 WHERE notify_admin IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_admin')
        batch_op.drop_column('notify_delete')
        batch_op.drop_column('notify_edit')
        batch_op.drop_column('notify_like')
    # ### end Alembic commands ###
