"""add blog_feeds, fish_count to blogs, Float for dried_fish and amount

Revision ID: c3a4f587e97a
Revises: 921dca7b5e98
Create Date: 2026-06-27 17:53:09.710263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a4f587e97a'
down_revision = '921dca7b5e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id', 'user_id', name='uq_blog_feed_user')
    )
    with op.batch_alter_table('blog_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_feeds_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_feeds_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fish_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('fish_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('dried_fish',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('dried_fish',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('fish_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('fish_count')

    with op.batch_alter_table('blog_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_feeds_user_id'))
        batch_op.drop_index(batch_op.f('ix_blog_feeds_blog_id'))

    op.drop_table('blog_feeds')
    # ### end Alembic commands ###
