"""add notification_sent to blog_likes

Revision ID: c4c950a806d6
Revises: 73a9f1b858f7
Create Date: 2025-09-04 17:21:17.571082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c950a806d6'
down_revision = '73a9f1b858f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空列
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))
    
    # 为现有记录设置默认值
    op.execute("UPDATE blog_likes SET notification_sent = 0 WHERE notification_sent IS NULL")
    
    # 然后将列设为NOT NULL
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.alter_column('notification_sent', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')

    # ### end Alembic commands ###
