"""empty message

Revision ID: cbf9e467bf1d
Revises: 7f96adcdf3c2
Create Date: 2025-11-07 22:35:40.899487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf9e467bf1d'
down_revision = '7f96adcdf3c2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'session_version',
                sa.Integer(),
                nullable=False,
                server_default='0',  # 给现有数据填 0
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    # ### end Alembic commands ###
