"""add_clipboard

Revision ID: e6c90c1ea618
Revises: 8de1b128cb9a
Create Date: 2026-01-17 20:49:17.507901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c90c1ea618'
down_revision = '8de1b128cb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipboards',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.Column('publicity', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clipboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clipboards_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipboards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipboards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipboards_ignore'), ['ignore'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipboards_publicity'), ['publicity'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipboards_title'), ['title'], unique=False)

    op.create_table('clip_text',
    sa.Column('clip_id', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clipboards.id'], ),
    sa.PrimaryKeyConstraint('clip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clip_text')
    with op.batch_alter_table('clipboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clipboards_title'))
        batch_op.drop_index(batch_op.f('ix_clipboards_publicity'))
        batch_op.drop_index(batch_op.f('ix_clipboards_ignore'))
        batch_op.drop_index(batch_op.f('ix_clipboards_id'))
        batch_op.drop_index(batch_op.f('ix_clipboards_created_at'))
        batch_op.drop_index(batch_op.f('ix_clipboards_author_id'))

    op.drop_table('clipboards')
    # ### end Alembic commands ###
