"""add Blog and BlogLike

Revision ID: ef691a7f20f9
Revises: 
Create Date: 2025-08-09 17:06:17.116869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef691a7f20f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogs_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_ignore'), ['ignore'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_title'), ['title'], unique=False)

    op.create_table('blog_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id', 'user_id', name='uq_blog_like_blog_user')
    )
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_likes_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_blog_likes_blog_id'))

    op.drop_table('blog_likes')
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_title'))
        batch_op.drop_index(batch_op.f('ix_blogs_ignore'))
        batch_op.drop_index(batch_op.f('ix_blogs_id'))
        batch_op.drop_index(batch_op.f('ix_blogs_created_at'))
        batch_op.drop_index(batch_op.f('ix_blogs_author_id'))

    op.drop_table('blogs')
    # ### end Alembic commands ###
