"""notifications

Revision ID: f63698f7f0bf
Revises: 067f8724cc18
Create Date: 2025-08-31 11:29:59.637105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63698f7f0bf'
down_revision = '067f8724cc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=1)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
